[{
    "backdrop_path": "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg",
    "id": 315162,
    "original_title": "Puss in Boots: The Last Wish",
    "overview": "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    "poster_path": "/lmf0zzR7ritjOL3qumRh3hfvOFK.jpg",
    "release_date": "2022-12-07",
    "title": "Puss in Boots: The Last Wish",
},
{
    "backdrop_path": "/53BC9F2tpZnsGno2cLhzvGprDYS.jpg",
    "id": 736526,
    "original_title": "Troll",
    "overview": "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
    "poster_path": "/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
    "release_date": "2022-12-01",
    "title": "Troll",
},
{
    "backdrop_path": "/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
    "id": 19995,
    "original_title": "Avatar",
    "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    "poster_path": "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    "release_date": "2009-12-15",
    "title": "Avatar",
},
{
    "backdrop_path": "/5wDBVictj4wUYZ31gR5WzCM9dLD.jpg",
    "id": 877269,
    "original_title": "Strange World",
    "overview": "A journey deep into an uncharted and treacherous land, where fantastical creatures await the legendary Clades—a family of explorers whose differences threaten to topple their latest, and by far most crucial, mission.",
    "poster_path": "/342jTVbBlkLPUvMgs4dcfA1fy7N.jpg",
    "release_date": "2022-11-23",
    "title": "Strange World",
},
{
    "backdrop_path": "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    "id": 505642,
    "original_title": "Black Panther: Wakanda Forever",
    "overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    "poster_path": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    "release_date": "2022-11-09",
    "title": "Black Panther: Wakanda Forever",
},
{
    "backdrop_path": "/qdFrqXYH6PtyAVlegub7bpoSgro.jpg",
    "id": 573171,
    "original_title": "Huevitos Congelados",
    "overview": "The rooster Toto has a new enemy: a pirate who plans to turn him into a cryogenically frozen rooster.",
    "poster_path": "/gBBCBMXKzWRADtliUYfV69aVIcz.jpg",
    "release_date": "2022-12-14",
    "title": "A Frozen Rooster",
},
{
    "backdrop_path": "/2T92w8l2iTnyG9jwOmIWfM9thRV.jpg",
    "id": 1045944,
    "original_title": "The Boss Baby: Christmas Bonus",
    "overview": "Christmas Eve takes a twisty turn when the Boss Baby accidentally swaps places with one of Santa's elves and gets stranded at the North Pole.",
    "poster_path": "/iMmMxF6f2OonUrXrHKBLSYAhXly.jpg",
    "release_date": "2022-12-06",
    "title": "The Boss Baby: Christmas Bonus",
},
{
    "backdrop_path": "/jauI01vUIkPA0xVsamGj0Gs1nNL.jpg",
    "id": 507086,
    "original_title": "Jurassic World Dominion",
    "overview": "Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.",
    "poster_path": "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    "release_date": "2022-06-01",
    "title": "Jurassic World Dominion",
}].forEach(async item=>{
  await addDoc(collection(db,"movies"),item)
})